// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWxXPLjKRsrtLN-yoIgyeOS_Y_g3UqnY0',
    appId: '1:1090525350625:web:40566748b9aa45c28005a0',
    messagingSenderId: '1090525350625',
    projectId: 'mehsimbhai-609b3',
    authDomain: 'mehsimbhai-609b3.firebaseapp.com',
    storageBucket: 'mehsimbhai-609b3.appspot.com',
    measurementId: 'G-PDRWN2JNP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBPPd_Hv08m6rXJfJs1a08VdBUatkDybw',
    appId: '1:1090525350625:android:5f4559c8544029e78005a0',
    messagingSenderId: '1090525350625',
    projectId: 'mehsimbhai-609b3',
    storageBucket: 'mehsimbhai-609b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG6EqVH2ou4plnfrtSFdxK0l1n77Y46Mg',
    appId: '1:1090525350625:ios:8f2ce3b27a25437a8005a0',
    messagingSenderId: '1090525350625',
    projectId: 'mehsimbhai-609b3',
    storageBucket: 'mehsimbhai-609b3.appspot.com',
    iosBundleId: 'com.example.ecomApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG6EqVH2ou4plnfrtSFdxK0l1n77Y46Mg',
    appId: '1:1090525350625:ios:8f2ce3b27a25437a8005a0',
    messagingSenderId: '1090525350625',
    projectId: 'mehsimbhai-609b3',
    storageBucket: 'mehsimbhai-609b3.appspot.com',
    iosBundleId: 'com.example.ecomApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWxXPLjKRsrtLN-yoIgyeOS_Y_g3UqnY0',
    appId: '1:1090525350625:web:edaeef173d51cac78005a0',
    messagingSenderId: '1090525350625',
    projectId: 'mehsimbhai-609b3',
    authDomain: 'mehsimbhai-609b3.firebaseapp.com',
    storageBucket: 'mehsimbhai-609b3.appspot.com',
    measurementId: 'G-FYFXN6JZVT',
  );
}
